#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-asv
Version  : 0.5.1
Release  : 3
URL      : https://files.pythonhosted.org/packages/5b/e4/f4af30aa6e75c12832f3d61cd07610510e2e47aaa1547513f4a51dd335b1/asv-0.5.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/5b/e4/f4af30aa6e75c12832f3d61cd07610510e2e47aaa1547513f4a51dd335b1/asv-0.5.1.tar.gz
Summary  : Airspeed Velocity: A simple Python history benchmarking tool
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-asv-bin = %{version}-%{release}
Requires: pypi-asv-license = %{version}-%{release}
Requires: pypi-asv-python = %{version}-%{release}
Requires: pypi-asv-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(six)
BuildRequires : pypi(wheel)

%description
=================
        
        **airspeed velocity** (``asv``) is a tool for benchmarking Python
        packages over their lifetime.
        
        It is primarily designed to benchmark a single project over its
        lifetime using a given suite of benchmarks.  The results are displayed
        in an interactive web frontend that requires only a basic static
        webserver to host.

%package bin
Summary: bin components for the pypi-asv package.
Group: Binaries
Requires: pypi-asv-license = %{version}-%{release}

%description bin
bin components for the pypi-asv package.


%package license
Summary: license components for the pypi-asv package.
Group: Default

%description license
license components for the pypi-asv package.


%package python
Summary: python components for the pypi-asv package.
Group: Default
Requires: pypi-asv-python3 = %{version}-%{release}

%description python
python components for the pypi-asv package.


%package python3
Summary: python3 components for the pypi-asv package.
Group: Default
Requires: python3-core
Provides: pypi(asv)
Requires: pypi(six)

%description python3
python3 components for the pypi-asv package.


%prep
%setup -q -n asv-0.5.1
cd %{_builddir}/asv-0.5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1644957775
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-asv
cp %{_builddir}/asv-0.5.1/LICENSE.rst %{buildroot}/usr/share/package-licenses/pypi-asv/8565420f58601d5de7f1124e5e20c2f6ab1a6a6b
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/asv

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-asv/8565420f58601d5de7f1124e5e20c2f6ab1a6a6b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
